# Generated by Django 4.2.1 on 2023-06-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=64)),
                ('link_name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
    ]
